# -*- coding: utf-8 -*-
"""Copy of decision_tree_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anyyW6wQVJCMriSXIobg-SV1wPiPBeyw

# Decision Tree Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Training the Decision Tree Regression model on the whole dataset"""

from sklearn.tree import DecisionTreeRegressor

tree_regressor = DecisionTreeRegressor(random_state=0)
tree_regressor.fit(X, y)

"""## Predicting a new result"""

tree_regressor.predict([[6.5]])

"""## Visualising the Decision Tree Regression results (higher resolution)"""

# increase grid resolution
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))

# real results
plt.scatter(X, y, color='red')

# plot polynomial predictions
y_pred = tree_regressor.predict(X_grid)

print(X_grid, y_pred)

plt.plot(X_grid, y_pred, color='blue')

# title & labels
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position Level')
plt.ylabel('Salary')

# show the graph
plt.show()