# -*- coding: utf-8 -*-
"""Copy of polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1024D-YTx3hB241HaRDFZt5VzQUN0kbLQ

# Polynomial Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Training the Linear Regression model on the whole dataset"""

from sklearn.linear_model import LinearRegression

linear_regressor = LinearRegression()
linear_regressor.fit(X, y)

"""## Training the Polynomial Regression model on the whole dataset"""

from sklearn.preprocessing import PolynomialFeatures

# y = b0 + b1x1 + b2x1^2
polynomial_regressor = PolynomialFeatures(degree=4)

X_poly = polynomial_regressor.fit_transform(X)

linear_regressor_2 = LinearRegression()
X_poly = linear_regressor_2.fit(X_poly, y)

"""## Visualising the Linear Regression results"""

# real results
plt.scatter(X, y, color='red')

# plot linear predictions
pred_y = linear_regressor.predict(X)
plt.plot(X, pred_y, color='blue')

# title & labels
plt.title('Truth or Bluff (Linear Regression)')
plt.xlabel('Position Level')
plt.ylabel('Salary')

# show the graph
plt.show()

"""## Visualising the Polynomial Regression results"""

# real results
plt.scatter(X, y, color='red')

# plot linear predictions
y_pred = linear_regressor_2.predict(polynomial_regressor.fit_transform(X))
plt.plot(X, y_pred, color='blue')

# title & labels
plt.title('Truth or Bluff (Polynomial Regression)')
plt.xlabel('Position Level')
plt.ylabel('Salary')

# show the graph
plt.show()

"""## Visualising the Polynomial Regression results (for higher resolution and smoother curve)"""

# real results
plt.scatter(X, y, color='red')

# increase grid resolution
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))

# plot polynomial predictions
y_pred = linear_regressor_2.predict(polynomial_regressor.fit_transform(X_grid))
plt.plot(X_grid, y_pred, color='blue')

# title & labels
plt.title('Truth or Bluff (Polynomial Regression)')
plt.xlabel('Position Level')
plt.ylabel('Salary')

# show the graph
plt.show()

"""## Predicting a new result with Linear Regression"""

linear_regressor.predict([[6.5]])

"""## Predicting a new result with Polynomial Regression"""

poly_reg_result = polynomial_regressor.fit_transform([[6.5]])
linear_regressor_2.predict(poly_reg_result)