# -*- coding: utf-8 -*-
"""Copy of random_forest_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMAyaNbkWnb_UbLqh-uEa2aWhBYfaR8O

# Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Training the Random Forest Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor

# n_estimators is the number of trees
forest_regressor = RandomForestRegressor(n_estimators=10, random_state=0)
forest_regressor.fit(X, y)

"""## Predicting a new result"""

forest_regressor.predict([[6.5]])

"""## Visualising the Random Forest Regression results (higher resolution)"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape(len(X_grid), 1)

plt.scatter(X, y, color='red')

y_pred = forest_regressor.predict(X_grid)
plt.plot(X_grid, y_pred, color='blue')
plt.title('Truth or Bluff (Random Forest Regression)')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()